name: Package version

on:
  workflow_call:
    outputs:
      pkg-version:
        value: ${{ jobs.increase-package-version.outputs.pkg-version }}
    inputs:
      version-type:
        default: patch
        required: false
        type: string
        description: "Value can be: patch, minor or major"

  workflow_dispatch:
    inputs:
      version-type:
        type: choice
        description: What version do you want to increase?
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  increase-package-version:
    name: ${{ inputs.version-type }}${{ github.event.inputs.version-type }} version
    runs-on: ubuntu-latest
    outputs:
      pkg-version: ${{ steps.pkg-version.outputs.current-version }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup git configuration
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Increase version
        run: |
          cd ./packages/contract-proxy-kit
          yarn version --${{ inputs.version-type }}${{ github.event.inputs.version-type }}
          cd ../..

      - name: Push commit
        run: git push origin master

      - name: Get the package version
        id: pkg-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: packages/contract-proxy-kit
