name: Publish
on:
  workflow_dispatch:
    inputs:
      version-type:
        type: choice
        description: What version do you want to increase?
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  increase-package-version:
    uses: ElvisKrop/contract-proxy-kit/.github/workflows/increase-package-version.yml@master
    with:
      version-type: ${{ github.event.inputs.version-type }}

  npm-publish:
    needs: increase-package-version
    name: Publish ${{ needs.increase-package-version.outputs.pkg-version }} to the NPM registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Get yarn cache
        uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build NPM Package
        run: yarn cpk:build

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: "./packages/contract-proxy-kit/package.json"
          token: ${{ secrets.NPM_TOKEN }}
