name: Publish
on: workflow_dispatch

jobs:
  increase-package-version:
    name: Increase package version automatically
    runs-on: ubuntu-latest
    outputs:
      pkg-version: ${{ steps.pkg-version.outputs.current-version }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup git configuration
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Push commit
        run: |
          # Stage the file, commit and push
          yarn cpk:patch-version
          git push origin master

      - name: Get the package version
        id: pkg-version
        uses: martinbeentjes/npm-get-version-action@master

  npm-publish:
    needs: increase-package-version
    name: Publish ${{ needs.increase-package-version.outputs.pkg-version }} to the NPM registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup cache key and directory for node_modules cache
        id: yarn-cache
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build NPM Package
        run: yarn cpk:build

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: "./packages/contract-proxy-kit/package.json"
          token: ${{ secrets.NPM_TOKEN }}
